# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=100)),
                ('animal_characteristics', models.TextField(max_length=400)),
                ('fur_colour', models.CharField(max_length=100)),
                ('fur_type', models.CharField(max_length=100)),
                ('white_marks', models.CharField(max_length=100)),
                ('eye_colour', models.CharField(max_length=100)),
                ('blue_eyed_white', models.CharField(max_length=50)),
                ('genotype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('animals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Animals')),
            ],
        ),
        migrations.CreateModel(
            name='Eggs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egg_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('animals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Animals')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_product', models.CharField(max_length=200)),
                ('food_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='MiscPurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misc_product', models.CharField(max_length=300)),
                ('misc_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('animals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Animals')),
            ],
        ),
    ]
