# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animals',
            options={'verbose_name_plural': 'Animals'},
        ),
        migrations.AlterModelOptions(
            name='eggs',
            options={'verbose_name_plural': 'Eggs'},
        ),
        migrations.AlterModelOptions(
            name='foodpurchases',
            options={'verbose_name_plural': 'FoodPurchases'},
        ),
        migrations.AlterModelOptions(
            name='miscpurchases',
            options={'verbose_name_plural': 'MiscPurchases'},
        ),
        migrations.AddField(
            model_name='animals',
            name='arrived',
            field=models.DateField(null=True, verbose_name='Ankommet'),
        ),
        migrations.AddField(
            model_name='animals',
            name='born',
            field=models.DateField(null=True, verbose_name='Født'),
        ),
        migrations.AddField(
            model_name='animals',
            name='departure',
            field=models.DateField(null=True, verbose_name='Afgang'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_date',
            field=models.DateField(null=True, verbose_name='Dato'),
        ),
        migrations.AddField(
            model_name='eggs',
            name='egg_date',
            field=models.DateField(null=True, verbose_name='Dato'),
        ),
        migrations.AddField(
            model_name='fat',
            name='fat_date',
            field=models.DateField(null=True, verbose_name='Dato'),
        ),
        migrations.AddField(
            model_name='foodpurchases',
            name='food_date',
            field=models.DateField(null=True, verbose_name='Dato for køb'),
        ),
        migrations.AddField(
            model_name='miscpurchases',
            name='misc_date',
            field=models.DateField(null=True, verbose_name='Dato for køb'),
        ),
        migrations.AddField(
            model_name='weights',
            name='weight_date',
            field=models.DateField(null=True, verbose_name='Dato vejet'),
        ),
    ]
