# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20160204_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='dead',
            field=models.BooleanField(default=False, verbose_name='Død?'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='departure',
            field=models.DateField(blank=True, null=True, verbose_name='Afgang'),
        ),
    ]
