# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20160204_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='fat',
            options={'verbose_name_plural': 'Fat'},
        ),
        migrations.AlterModelOptions(
            name='weights',
            options={'verbose_name_plural': 'Weights'},
        ),
    ]
